### PR TITLE
Sinan's updates

### PR DESCRIPTION
**Pull request by sinanOguz**
VID and PID added for IZONE UVC 5M camera

### CODE REVIEW

**Comment by allsey87** [comment]
Which camera is this PID and VID for? Is this a permanent solution or just for testing?

**Comment by sinanOguz** [comment]
The new camera's name is "IZONE UVC 5M". So this PR is for the new camera.

Permanent.

**Comment by allsey87** [comment]
I think the old udev entries should be removed. It is not a good idea to have more than one rule that generates a symlink to `/dev/cameraX`.

**Comment by allsey87** [comment]
I have solved this in 7da90f7650521f674e5032cdcb333a8373dd3093 by not specifying the vendor and product IDs. Could you check if this works on your end @sinanOguz

**Pull request closed without merging**
